name = "csv-ai-agent"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "c8431a7fe1ca4ebd91ef43ce29fe11a7"
preview_id = "9c8730d7380746acb4deb2bf032cd64b"

# R2 bucket for high-performance data storage
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "csv-ai-agent-data"

[vars]
ENVIRONMENT = "production"
# NVIDIA_API_KEY is now set as a secret via: wrangler secret put NVIDIA_API_KEY

# Add NVIDIA API key as a secret variable
# Run: wrangler secret put NVIDIA_API_KEY
# Or set in wrangler.toml vars section for development:
# NVIDIA_API_KEY = "your_key_here"